version: 0.2

env:
  shell: bash
  exported-variables:
    - OUTPUT

phases:
  pre_build:
    commands:
      ${env_vars_snippet}
      ${assume_role_snippet}

  build:
    commands:
      - aws autoscaling start-instance-refresh --auto-scaling-group-name $SRC --region ${aws_region}
