version: 0.2

env:
  shell: bash
  exported-variables:
    - OUTPUT

phases:
  install:
    commands:
      - npm install

  # pre_build:
  #   commands:
  #     - npm run test
      
  build:
    commands:
      - npm run build
      
artifacts:
  base-directory: public
  files:
    - '**/*'
