version: 0.2

env:
  shell: bash
  exported-variables:
    - OUTPUT

phases:
  install:
    commands:
      - cd $SRC
      - tfswitch || echo .
      ${env_vars_snippet}

  pre_build:
    commands:
      - export TF_INPUT=0
      - |
        if [ ! -z $TF_WORKSPACE ]
        then
          terraform workspace list | grep $TF_WORKSPACE || terraform workspace new $TF_WORKSPACE
        fi
      - terraform init

  build:
    commands:
      - terraform apply -auto-approve $(eval "echo $ARGS")
      - OUTPUT=$(terraform output -json | jq 'to_entries[] | {(.key):(.value.value)}' | jq -s add)
